name: Trigger auto deployment for testing-oidc-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/testing-oidc-app-AutoDeployTrigger-cbead8e6-e9ed-45d3-a894-ba45ecae386e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTINGOIDCAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTINGOIDCAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTINGOIDCAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: testingoidcregistry.azurecr.io
          registryUsername: ${{ secrets.TESTINGOIDCAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINGOIDCAPP_REGISTRY_PASSWORD }}
          containerAppName: testing-oidc-app
          resourceGroup: testing-oidc-rg
          imageToBuild: testingoidcregistry.azurecr.io/testing-oidc-app:${{ github.sha }}
          dockerfilePath: Dockerfile


